-- Identity. One row per authenticated human, keyed on (issuer, subject) rather than subject alone:
-- sub is unique only within an issuer, and federating with a deployer's own IdP is a first-class
-- scenario for a multi-cloud framework (spec-patch-06 section 4.1).
--
-- subject is opaque and email is a mutable attribute, never the key -- people change addresses and
-- principal_id must survive that (section 4.2). Nothing outside this table stores subject or email.
create table road_principals (
  principal_id           number generated by default as identity primary key,
  issuer                 varchar2(512 char) not null,
  subject                varchar2(255 char) not null,
  email                  varchar2(320 char),
  display_name           varchar2(255 char),
  status                 varchar2(20 char) default 'ACTIVE' not null,
  credentials_changed_at timestamp with time zone,
  created_at             timestamp with time zone default systimestamp not null,
  updated_at             timestamp with time zone default systimestamp not null,
  constraint road_principals_iss_sub_uk unique (issuer, subject),
  constraint road_principals_status_ck
    check (status in ('ACTIVE', 'SUSPENDED', 'RETIRED'))
);
