create table ui_assets (
  asset_id        number generated by default as identity primary key,
  app_name        varchar2(128 char) not null,
  relative_path   varchar2(1024 char) not null,
  file_name       varchar2(255 char) not null,
  content_type    varchar2(255 char) not null,
  content_length  number not null,
  checksum        varchar2(64 char),
  updated_at      timestamp with time zone default systimestamp not null,
  content         blob not null,
  constraint ui_assets_app_path_uk unique (app_name, relative_path)
)
lob (content) store as securefile (
  compress medium
  cache reads
);
