whenever oserror exit failure rollback
whenever sqlerror exit sql.sqlcode rollback

-- INTENT:
-- Purpose: Define the ORDS modules, templates and handlers for the framework scaffold.
-- Approach: Invoke each module create script plus its privileges script under api/modules/.
-- Reason: ORDS metadata is versioned as code rather than configured by hand, so a
--   schema rebuild reproduces the API surface exactly.
-- Expected objects:
--   ORDS modules: health, auth, session, ui (plus privilege definitions)
-- Risk: Low. Module creates delete and recreate their module, so in-flight requests
--   against a live environment may briefly 404.
-- Prior history checked: Search db-history for prior 90_rest runs in this environment.
-- END INTENT

prompt === deploy ords modules ===
@api/modules/health/module.create.sql
@api/modules/health/privileges.create.sql

-- The scaffold's public login surface -- /jwt-auth/login and its JWKS document -- is the one
-- ORDS-level object spec-patch-09 section 2 actually needs to be ABSENT, not merely unused, under
-- external_oidc: everything else in the scaffold's namespace (its packages, its tables) is inert
-- once the JWT profile registered above trusts a different issuer, because ORDS validates only
-- against whichever profile is registered -- a token the scaffold could still mint would simply
-- fail that check. A reachable public endpoint that mints tokens is a different kind of residue,
-- so this indirection exists to remove it rather than leave it merely pointless. Generated by
-- bin/render-auth-config.sh from AUTH_PROFILE: the two real includes under
-- ords_local_jwt_scaffold, nothing at all under external_oidc.
@deploy/create/90_rest_auth.generated.sql

@api/modules/session/module.create.sql
@api/modules/session/privileges.create.sql
@api/modules/ui/module.create.sql
@api/modules/ui/privileges.create.sql
@api/modules/admin/module.create.sql
@api/modules/admin/privileges.create.sql
